
##Background and Objective:
# A nationwide survey of hospital costs conducted by the US Agency for Healthcare consists of hospital records of inpatient samples. 
# The given data is restricted to the city of Wisconsin and relates to patients in the age group 0-17 years. 
# The agency wants to analyze the data to research on healthcare costs and their utilization

# Domain: Healthcare

# Analysis to be done: 

# 1. To record the patient statistics, the agency wants to find the age category of people who frequently visit the hospital and has the maximum expenditure.

# 2. In order of severity of the diagnosis and treatments and to find out the expensive treatments, the agency wants to find the diagnosis-related group that has maximum hospitalization and expenditure.

# 3. To make sure that there is no malpractice, the agency needs to analyze if the race of the patient is related to the hospitalization costs.

# 4. To properly utilize the costs, the agency has to analyze the severity of the hospital costs by age and gender for the proper allocation of resources.

# 5. Since the length of stay is the crucial factor for inpatients, the agency wants to find if the length of stay can be predicted from age, gender, and race.

# 6. To perform a complete analysis, the agency wants to find the variable that mainly affects hospital costs.

## Analysis Tasks: 


## Geting and print current working directory.
print(getwd())


## 1.Import data into R environment
## Importing Data 

install.packages("readxl")

library("readxl")
data <- read_excel("C:/Users/nawin/hospital_data.xlsx")
## Printing Dataset
print(data)

## Printing column names
colnames(data)
# Observation: "AGE"    "FEMALE" "LOS"    "RACE"   "TOTCHG" "APRDRG"
# "TOTCHG":  Hospital discharge costs
# Aprdrg: All Patient Refined Diagnosis Related Groups
# Los	Length of stay in days

##  Printing rows and columns 
print(ncol(data))
## observation: There are 12 columns
print(nrow(data))
## observation: There are 2224 rows

summary(data)

# 1. To record the patient statistics, the agency wants to find the age category of people who frequently visit the hospital and has the maximum expenditure.

## Fetching number of hospitals visits based on age 
summary(as.factor(data$AGE))
## Observation :
# There are 307 number of visits for age 0 to 1
# There are 10 number of visits for age 1 to 2
# There are 1 number of visits for age 2 to 3
# There are 3 number of visits for age 3 to 4
# There are 2 number of visits for age 4 to 5
# There are 2 number of visits for age 5 to 6
# There are 2 number of visits for age 6 to 7
# There are 3 number of visits for age 7 to 8
# There are 2 number of visits for age 8 to 9
# There are 2 number of visits for age 9 to 10
# There are 4 number of visits for age 10 to 11
# There are 8 number of visits for age 11 to 12
# There are 15 number of visits for age 12 to 13
# There are 18 number of visits for age 13 to 14
#There are 25 number of visits for age 14 to 15
# There are 29 number of visits for age 15 to 16
# There are 29 number of visits for age 16 to 17
# There are 38 number of visits for age 17 to 18

# Plotting the number of hospital visits and the age group
hist(data$AGE, main="Histogram of Age Group and their hospital visits",xlab="Age group", border="black", col=c("blue", "dark green"), xlim=c(0,20), ylim=c(0,350))
# Observation: Age group of 0 to 1 years have maximum times visited the hospital

## Summing Expenditure on basics of age group
expenditure_Age = aggregate(TOTCHG ~ AGE, FUN=sum, data=data)

## Fetching maximum expenses with age group
maxexp_age=which.max(tapply(expenditure_Age$TOTCHG, expenditure_Age$TOTCHG, FUN=sum))
maxexp_age
# Observation: Maximun expense is 678118 and in age group of 17 to 18 

## 2. In order of severity of the diagnosis and treatments and to find out the expensive treatments, 
# the agency wants to find the diagnosis-related group that has maximum hospitalization and expenditure.
# Fetching the diagnosis-related group and its hospitalization expenditure
summary(as.factor(data$APRDRG))
diagnostic_Cost = aggregate(TOTCHG ~ APRDRG, FUN = sum, data = data)

#Fetching  the max diagnostic cost
max_diagnostic_Cost=diagnostic_Cost[which.max(diagnostic_Cost$TOTCHG), ]
max_diagnostic_Cost
# Observation: 
# There are 640 "APRDRG(All Patient Refined Diagnosis Related Groups)" and 437978 "TOTCHG(Hospital discharge costs)"

## 3. To make sure that there is no malpractice, the agency needs to analyze if the race of the patient is related to the hospitalization costs.
summary(as.factor(data$RACE))
#Observation: Presence of null value , so have to remove it
data = na.omit(data)
summary(as.factor(data$RACE))
#Observation" There are 484 patients in age group of 1
# Data is positively skewed

#Co-relation between Race of the Patient and Hospitalization Costs
# By Linear Regression
race_hospcosts=lm(TOTCHG~ RACE, data=data)
summary(race_hospcosts)
# Observation: p value is 0.6856
# Since pvalue is greater than 0.05 
# so no correlation between Race of the Patient and Hospitalization Costs
# So, hospital has no malpractice

## 4.To properly utilize the costs,
# the agency has to analyze the severity of the hospital costs
# by age and gender for the proper allocation of resources.

## Summary by gender

library(dplyr)
n_distinct(data$FEMALE)
#Observation: There are 2 distinct values
data %>% distinct(FEMALE)

#Correlation exits between hospital costs and AGE
age_hospcosts=lm(TOTCHG~ AGE, data=data)
summary(age_hospcosts)
## P value is 0.00333 , less than 0.05
# so, correlation exits between hospital costs and AGE 

#Correlation exits between hospital costs and Gender
gender_hospcosts=lm(TOTCHG~ FEMALE, data=data)
summary(gender_hospcosts)
## P value is 0.1849 , less than 0.05
# so, correlation exits between hospital costs and Gender

## 5. Since the length of stay is the crucial factor for inpatients, 
# the agency wants to find if the length of stay can be predicted from age, gender, and race.

#Checking correlation between Length of Stay and gender
gender_los=lm(LOS~ FEMALE, data=data)
summary(gender_los)
#Observation: p-value is 0.4187 , so no correlation between Length of stay and gender of patients.

#Checking correlation between Length of Stay and AGE
gender_age1=lm(LOS~ AGE, data=data)
summary(gender_age1)
#Observation: p-value is 0.1235 greater than 0.05 , so no correlation between Length of stay and race of patients.

#Checking correlation between Length of Stay and RACE
gender_race=lm(LOS~ RACE, data=data)
summary(gender_race)
#Observation: p-value is 0.6917 greater than 0.05 , so no correlation between Length of stay and race of patients.
# So, race , gender , age cannot predict length of stay of patients

##6.  To perform a complete analysis, the agency wants to find the variable that mainly affects hospital costs.

## 
aov(TOTCHG ~.,data=data)
mod <- lm(TOTCHG ~ .,data=data)
summary(mod)
## Observation:
# P values of Gender, Race are more than 0.05 , so these do not affect hospitilaztion costs
# P values of Age, Length of stay, All Patient Refined Diagnosis Related Groups are less than 0.05 , so these affects hospitilazition costs
